packages:
  - docs
  - examples/*
  - packages/*
catalog:
  '@unocss/astro': ^0.62.3
  '@unocss/core': ^0.62.3
  '@unocss/eslint-plugin': ^0.62.3
  '@unocss/preset-mini': ^0.62.3
  '@unocss/preset-uno': ^0.62.3
  '@unocss/preset-web-fonts': ^0.62.3
  '@unocss/vite': ^0.62.3
